routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::GET('/','PageController@getIndex');
Route::GET('/about','PageController@getAbout');
Route::GET('/contact','PageController@getContact');
Route::get('/home', 'HomeController@index')->name('home');


Route::group(['middleware'=>['web']],function(){
	Route::resource('notice','NoticeController');
	Route::resource('event','EventController');	
});


/*Route::GET('/events','PageController@getEvents');
Route::GET('/notices','PageController@getNotices');
Route::GET('/mission','PageController@getMission');
Route::GET('/helpsupport','PageController@getHelpSupport');
Route::GET('/programs','PageController@getPrograms');
*/
Auth::routes();

app/Notice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Notice extends Model
{
    //
}

app/Http/Controllers/NoticeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Notice;
use Session;
use Image;

class NoticeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $notices = Notice::all();
        return view('notice.index')->withNotices($notices);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('notice.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Validating the data enterd by the user!!
        $this->validate($request,array(
                'title' => 'required|max:255',
                'body'  => 'required'
            ));

        //Storing the data to the database after propoer validation check
        $notice = new Notice;
        //Saving the notice contents
        $notice->title = $request->title;
        $notice->body  = $request->body;

        //saving the image
        if($request->hasFile('image')){
            $image = $request->file('image');
            $filename = time() . '.' . $image->getClientOriginalExtension();
            $location = public_path('images/' . $filename);
            Image::make($image)->resize(1000,1000)->save($location);
            $notice->image = $filename;
        }

        $notice->save();
        Session::flash('success','The Notice was successfully saved!!');

        //Redirecting the user to proper route
        return redirect()->route('notice.show',$notice->id);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $notice = Notice::find($id);
        return view('notice.show')->with('notice',$notice);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //Find the notice in the database and save it as a variable
        $notice = Notice::find($id);

        //return the view and pass in the variable 
        return view('notice.edit')->withNotice($notice);
}

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/notice/create.blade.php
@extends('layouts.home')
@section('title','Create Notice')

@section('form')
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h1>Create New Notice</h1>
			<hr>
			<form class="form-group" method="POST" action="{{route('notice.store')}}" enctype="multipart/form-data">
				{{ csrf_field() }}
				<div>				
					<label for="title" class="form-group">Notice Title:</label>
					<div class="input-group">
						<span class="input-group-addon" id="basic-addon1"><i class="fa fa-pencil"></i></span>
						<input name="title" type="text" class="form-control" placeholder="Notice Title" aria-describedby="basic-addon1">
					</div>
				</div>
				<br>
				<div>
					<label for="image">Images for Notice:</label>
					<input type="file" name="image">
				</div>
				<br>
				<div>
					<label for="body" class="form-group">Notice Description:</label>
					<div class="input-group">
						<span class="input-group-addon" id="basic-addon1"><i class="fa fa-keyboard-o"></i></span>
						<textarea name="body" id="body" cols="30" rows="15" class="form-control" placeholder="Type the notice description here!!"></textarea>
					</div>
				</div>
				<br>
				<div>
					<button class="btn btn-success btn-lg btn-block">Create Post</button>
				</div>

			</form>
		</div>
	</div>
</div>
@endsection

resources/views/notice/index.blade.php
@extends('layouts.home')
@section('title','View all Notices')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1 class="text-center">All Notices</h1>
				<hr>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<table class="table">
					<thead>
						<th>#</th>
						<th>Title</th>
						<th>Body</th>
						<th>Created At:</th>
						<th></th>
					</thead>
					<tbody>
						@foreach ($notices as $notice)
							<tr>
								<th> {{ $notice->id }}</th>
								<td> {{ $notice->title }} </td>
								<td> {{ substr($notice->body, 0, 50)}} {{ strlen($notice->body) > 50 ? "...":" " }} </td>
								<td> {{date('M j, Y',strtotime($notice->created_at))}} </td>
								<td><a href="#"class="btn btn-default">View</a> <a href="#" class="btn btn-default">Edit</a>  <a href=""class="btn btn-default" >Delete</a></td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>		
	</div>
@stop

resources/views/notice/show.blade.php
@extends('layouts.home')
@section('title','View Notice')

@section('newnotice')
<div class="container-fluid">
	<div class="col-md-8 col-md-offset-2">
		<div class="content">
			<div class="row">
				<div class="card">
					<div class="header">
					<h4 class="title">{{$notice->title}}</h4>
						<p class="category">Uploaded by: {{ Auth::user()->name }} </p>
						<hr>
					</div>
					<div class="content">
						<div class="description chart-legend">
							@if ($notice->image)
								<img src=" {{asset('images/'.$notice->image)}} height="700" width="400" ">
								<br><br>
								<a href="{{asset('images/'.$notice->image)}}" style="color:blue;">View Full Picture</a>
							@endif
							<hr>
							<article> {{ $notice->body }} </article>
						</div>
						<div class="footer">
							<hr>
							<div class="stats">
								<i class=""></i> Updated at: {{ date('M j, y h:ia',strtotime($notice->updated_at)) }}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection