routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::GET('/','PageController@getIndex');
Route::GET('/about','PageController@getAbout');
Route::GET('/contact','PageController@getContact');
Route::get('/home', 'HomeController@index')->name('home');


Route::group(['middleware'=>['web']],function(){
	Route::resource('notice','NoticeController');
	Route::resource('event','EventController');	
});


/*Route::GET('/events','PageController@getEvents');
Route::GET('/notices','PageController@getNotices');
Route::GET('/mission','PageController@getMission');
Route::GET('/helpsupport','PageController@getHelpSupport');
Route::GET('/programs','PageController@getPrograms');
*/
Auth::routes();

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    @include('partials._head')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <br>
        <br>
        
        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>

</body>
</html>

resources/views/layouts/home.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	@include('partials._head')
</head>
<body>


	<div class="container-fluid">
		<div class="row">
			<header class="main-header">
				<nav id="navbar" class="navbar navbar-static-top">
					<div class="navbar-main">
						<div class="container">
							<div class="navbar-header">
								<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
									<span class="sr-only">Toggle navigation</span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
								</button>
								<a class="navbar-brand" href="index.html"><img src="#" alt=""></a>
							</div>
							<div id="navbar" class="navbar-collapse collapse pull-right">
								<ul class="nav navbar-nav">
									<li><a class="is-active" href="/">Home</a></li>
									<li><a href="/about">About</a></li>
									<li class="has-child"><a href="#">Events</a>
										<ul class="submenu">
											<li class="submenu-item"><a href="{{route('event.create')}}">Create</a></li>
											<li class="submenu-item"><a href=" {{route('event.index')}} ">View All </a></li>
											<li class="submenu-item"><a href="causes-single.html">Delete</a></li>
										</ul>
									</li>
									<li class="has-child"><a href="#">Notices</a>
										<ul class="submenu">
											<li class="submenu-item"><a href="{{ route('notice.create') }}">Create</a></li>
											<li class="submenu-item"><a href=" {{route('notice.index')}} ">View All</a></li>
											<li class="submenu-item"><a href="#">Delete</a></li>
										</ul>
									</li>
									<li><a href="#">Gallery</a></li>
									<li><a href="/contact">Contact</a></li>
									<li class="has-child">
										<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
											{{ Auth::user()->name }} <span class="caret"></span>
										</a>
										<ul class="submenu">
											<li class="submenu-item">
												<a href="{{ route('logout') }}"
												onclick="event.preventDefault();
												document.getElementById('logout-form').submit();">
												Logout
											</a>
											<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
												{{ csrf_field() }}
											</form>
											</li>
										</ul>
									</li>
								</ul>
							</div> <!-- /#navbar -->
						</div> <!-- /.container -->
					</div> <!-- /.navbar-main -->
				</nav> 
			</header> <!-- /. main-header -->	
		<br>
		<br>
		<div class="container">
			@include('partials._message')			
		</div>
		@yield('newnotice')
		@yield('newevent')
		@yield('content')
		@yield('form')
		<footer class="main-footer">
			<!-- Include _bottomfooter.blade.php -->
			@include('partials._bottomfooter')
		</footer> <!-- main-footer -->
	</div>
</div>



</body>
</html>

resources/views/layouts/index.blade.php
<!DOCTYPE html>
<html class="no-js">
<head>
    <!-- Include _head.blade.php -->
    @include('partials._head')

</head>

<body>


    <header class="main-header">
        
        
        <nav class="navbar navbar-static-top">

            <!-- Include _topnav.blade.php -->
            @include('partials._topnav')
            <!-- Include _navmain.blade.php -->
            @include('partials._navmain')
            


        </nav> 

    </header> <!-- /. main-header -->




    <!--   ****    Carousel  ***  ================================================== -->
    

    <!--         Include _carousel.blade.php -->
    @yield('carousel')

    <!-- /.carousel -->

    @yield('about')
    @yield('contact')

    <!-- Include _feature.blade.php -->
    @yield('features') 


    <!-- /.about-us -->


    <!-- Include _extra.blade.php -->
    @yield('extras')
    <!-- /.home-reasons -->




    <!-- Include _causes.blade.php -->
    @yield('causes')
    <!-- /.our-causes -->

    



    <!-- Include _supporter.blade.php -->
    @yield('supporters')
    <!-- /.our-sponsors -->


    


    <footer class="main-footer">

      <!-- Include _topfooter.blade.php  -->  
      @include('partials._topfooter')     

      <!-- Include _mainfooter.blade.php -->
      @include('partials._mainfooter')

      <!-- Include _bottomfooter.blade.php -->
      @include('partials._bottomfooter')

      

      
      
  </footer> <!-- main-footer -->



  <!-- Include Donate Modal _donate.blade.php -->
  @include('partials._donate')
  





    <!--  Scripts
    ================================================== -->

    <!-- jQuery -->
    <!-- Include _scripts.blade.php -->
    @include('partials._scripts')

</body>
</html>