routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::GET('/','PageController@getIndex');
Route::GET('/about','PageController@getAbout');
Route::GET('/contact','PageController@getContact');
Route::get('/home', 'HomeController@index')->name('home');


Route::group(['middleware'=>['web']],function(){
	Route::resource('notice','NoticeController');
	Route::resource('event','EventController');	
});


/*Route::GET('/events','PageController@getEvents');
Route::GET('/notices','PageController@getNotices');
Route::GET('/mission','PageController@getMission');
Route::GET('/helpsupport','PageController@getHelpSupport');
Route::GET('/programs','PageController@getPrograms');
*/
Auth::routes();

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    //
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Event;
use Session;
use Image;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $events = Event::all();
        return view('event.index')->withEvents($events);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('event.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Validating the data input by the user
        $this->validate($request,array(
                'title' => 'required|max:255',
                'body'  => 'required'
            ));

        //Storing the data to the database after a proper validation
        $event = new Event;

        $event->title = $request->title;
        $event->body  = $request->body;

        if($request->hasFile('image')){
            $image = $request->file('image');
            $filename = time(). '.' . $image->getClientOriginalExtension();
            $location = public_path('images/'.$filename);
            Image::make($image)->resize(1000,1000)->save($location);
            $event->image = $filename;
        }

        $event->save();

        Session::flash('success','The event has been successfully saved!!');

        //Redirecting the user to a proper route
        return redirect()->route('event.show',$event->id);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $event = Event::find($id);
        return view('event.show')->with('event',$event);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $event = Event::find($id);
        return view('event.edit')->withEvent($event);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,array(
                'title' => 'required|max:255',
                'body'  => 'required'
            ));
        $event = Event::find($id);
        $event->title = $request->input('title');
        $event->body = $request->input('body');

        $event->save();

        Session::flash('success','This post was successfully updated!!');
        return redirect()->route('event.show',$event->id);
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/event/create.blade.php
@extends('layouts.home')
@section('title','Create Events')

@section('form')
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h1>Create New Event</h1>
			<hr>
			<form class="form-group" method="POST" action="{{route('event.store')}}" enctype="multipart/form-data">
				{{ csrf_field() }}
				<div>				
					<label for="title" class="form-group">Event Title:</label>
					<div class="input-group">
						<span class="input-group-addon" id="basic-addon1"><i class="fa fa-pencil"></i></span>
						<input name="title" type="text" class="form-control" placeholder="Event Title" aria-describedby="basic-addon1">
					</div>
				</div>
				<br>
				<div>
					<label for="image">Images for Events:</label>
					<input type="file" name="image">
				</div>
				<br>
				<div>
					<label for="body" class="form-group">Event Description:</label>
					<div class="input-group">
						<span class="input-group-addon" id="basic-addon1"><i class="fa fa-keyboard-o"></i></span>
						<textarea name="body" id="body" cols="30" rows="15" class="form-control" placeholder="Type the event description here!!"></textarea>
					</div>
				</div>
				<br>
				<div>
					<button class="btn btn-success btn-lg btn-block">Create Event</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/event/edit.blade.php
@extends('layouts.home')
@section('title','Create Events')

@section('form')
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h1>Edit Event</h1>
			<hr>
			<form class="form-group" method="PATCH" action="{{route('event.update',$event->id)}}" enctype="multipart/form-data">
				<div>				
					<label for="title" class="form-group">Event Title:</label>
					<div class="input-group">
						<span class="input-group-addon" id="basic-addon1"><i class="fa fa-pencil"></i></span>
						<input name="title" type="text" class="form-control" value=" {!! $event->title !!} " aria-describedby="basic-addon1">
					</div>
				</div>
				<br>
				<div>
					<label for="image">Images for Event:</label>
					<input type="file" name="image">
				</div>
				<br>
				<div>
					<label for="body" class="form-group">Event Description:</label>
					<div class="input-group">
						<span class="input-group-addon" id="basic-addon1"><i class="fa fa-keyboard-o"></i></span>
						<textarea name="body" id="body" cols="30" rows="15" class="form-control" >{!! $event->body !!}</textarea>
					</div>
				</div>
				<br>
				<div>
					<button class="btn btn-success btn-lg btn-block">Create Event</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/event/index.blade.php
@extends('layouts.home')
@section('title','View all Events')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1 class="text-center">All Events</h1>
				<hr>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<table class="table">
					<thead>
						<th>#</th>
						<th>Title</th>
						<th>Body</th>
						<th>Created At:</th>
						<th></th>
					</thead>
					<tbody>
						@foreach ($events as $event)
							<tr>
								<th> {{ $event->id }} </th>
								<td> {{ $event->title }} </td>
								<td> {{ substr($event->body,0,50)}} {{ strlen($event->body) > 50 ? "...":" "}} </td>
								<td> {{ date('M j,Y',strtotime($event->created_at)) }} </td>
								<td><a href="{{route('event.show',$event->id)}}"class="btn btn-default">View</a> <a href="{{route('event.edit',$event->id)}}" class="btn btn-default">Edit</a>  <a href=""class="btn btn-default" >Delete</a></td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>		
	</div>
@stop

resources/views/event/show.blade.php
@extends('layouts.home')
@section('title','View Event')

@section('newevent')
<div class="container-fluid">
	<div class="col-md-8 col-md-offset-2">
		<div class="content">
			<div class="row">
				<div class="card">
					<div class="header">
					<h4 class="title">{{$event->title}}</h4>
						<p class="category">Uploaded by: {{ Auth::user()->name }} </p>
						<hr>
					</div>
					<div class="content">
						<div class="">
							@if ($event->image)
							<img class="" src="{{ URL::asset('images/'.$event->image) }}" height="700" width="400">
							<br>
							<a target="_blank" href="{{URL::asset('images/'.$event->image)}}">Viwe Pic</a>
							@endif
							<article class="text-center	">{{ $event->body}}</article>
						</div>
					
						<div class="footer">
							<div class="stats">
								<i class=""></i>Uploaded at: {{ date('M j, Y h:ia',strtotime($event->created_at)) }}
								<br>
								<i class=""></i>Updated at: {{ date('M j, Y h:ia',strtotime($event->updated_at)) }}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection